export { Dashboard } from "./Dashboard"
export { StaffHome } from "./StaffHome"; 
export { Login } from "./Login"
export { Cal } from './Cal'
export { TaskPortal } from "./TaskPortal"
export { TaskAllocate } from "./TaskAllocate"
export { Profile } from "./Profile"
export { ToDoList } from "./ToDoList"
export { HodDash } from "./HodDash"
export { HodHome } from "./HodHome"
export { TaskApproval } from "./TaskApproval"
export { FacultyOverview } from "./FacultyOverview"